export const PATH_PUBLIC = {
  home: "/",
  register: "/register",
  login: "/login",
  unauthorized: "/unauthorized",
  notFound: "/404",
};

export const PATH_DASHBOARD = {
  dashboard: "/dashboard",
  usersManagement: "/dashboard/users-management",
  updateRole: "/dashboard/update-role/:userName",
  sendMessage: "/dashboard/send-message",
  inbox: "/dashboard/inbox",
  allMessages: "/dashboard/all-messages",
  systemLogs: "/dashboard/system-logs",
  myLogs: "dashboard/my-logs",
  owner: "/dashboard/owner",
  admin: "/dashboard/admin",
  manager: "/dashboard/manager",
  user: "/dashboard/user",
  payments: "/dashboard/payments",
  paymentMethods: "/dashboard/payment-methods",
  invoice: "/dashboard/invoices",
  reservations: "/dashboard/reservations",
  parkingSpot: "/dashboard/parkingSpots",
  parkingReservationManagers: "/dashboard/parkingReservationManagers",
  parkingSpace:"/dashboard/parkingSpaces",
  availabilityMonitor:"/dashboard/availabilityMonitors",
  parkingSpaceManager:"/dashboard/parkingSpaceManagers",
};
